config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :diretorios do
    member do
      delete :delete_diretorio
    end
  end

  get 'perfil', to: 'perfil#perfil'
  patch 'editprofile', to: 'perfil#editprofile'
  get 'meusDiretorios', to:'diretorios#userDirectories'
  get 'menu', to: 'welcome#index'
  get 'signup', to: 'registrations#new'
  get 'login', to: 'registrations#login'
  get 'loginTest', to: 'registrations#loginTest'
  get 'campi', to: 'campi#index'
  post 'login', to: 'registrations#makeLogin'
  post 'signup', to: 'registrations#create'
  delete 'logout', to: 'sessions#destroy'
  resources :registrations


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :buscar_diretorio
  get 'buscar', to: 'buscar#new'
  post 'buscar', to: 'buscar#show'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'

  resources :about_page
  get 'about', to: 'about#index'
  post 'about', to: 'about#create'

  resources :upload_files


end

app/models/about.rb
class About < ApplicationRecord
  validates :sugestao, presence: { message: "Sua sugestão foi recebida por nossa equipe, agradecemos a colaboração!"}
  validates :sugestao, presence: { message: "É obrigatório inserir algum texto no campo de sugestões!"}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buscar.rb
class Buscar < ApplicationRecord
    validates :buscar, presence: { message: "Por favor insira nome válido" }
    validates :buscar, presence: {message: "Diretório não encontrado, por favor tente novamente."}
end

app/models/campi.rb
class Campi < ApplicationRecord
  validates :name, presence: { message: 'É obrigatório informar o nome!'}
  validates :name, format: { :with => /\A[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]\Z/,
                             :message => 'Nome inválido. Não é permitido a utilização dos caracteres especiais'}
  ##validates :name, format: { :with => /A(?!root$)z/,
  ##                          :message => 'Nome reservado. root é o nome para o diretório raiz'}

end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/diretorio.rb
class Diretorio < ApplicationRecord
  validates :name, presence: { message: 'É obrigatório informar o nome!'}
  validates :name, format: { :with => /\A[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]\Z/,
    :message => 'Nome inválido. Não é permitido a utilização dos caracteres especiais'}
  ##validates :name, format: { :with => /A(?!root$)z/,
  ##                          :message => 'Nome reservado. root é o nome para o diretório raiz'}


  def get_root_directory_id
    @diretorio_root = Diretorio.where(name: 'root').ids[0]

    if @diretorio_root == nil
      create_root_directory.id
    else
      @diretorio_root
    end
  end

  def get_root_directory
    @root_id = get_root_directory_id

    if @root_id == nil
      create_root_directory
    else
      Diretorio.find(@root_id)
    end
  end

  def create_root_directory
    @diretorio_root = Diretorio.new({name: 'root', path: '/'})
    @diretorio_root.save
    @diretorio_root
  end
end

app/models/diretorios_mapa.rb
class DiretoriosMapa < ApplicationRecord
  def get_parent_directory(directory_id)
    if directory_id == Diretorio.new.get_root_directory_id
      Diretorio.new.get_root_directory
    else
      @diretorio_mapa = DiretoriosMapa.find_by(child: directory_id)

      if @diretorio_mapa != nil
        return Diretorio.where(id: @diretorio_mapa[:parent])[0]
      else
        return Diretorio.new.get_root_directory
      end
    end
  end

  def parent_is_root(directory_id)
    get_parent_directory(directory_id).id == Diretorio.new.get_root_directory_id
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :name, presence: { message: 'É obrigatório informar o nome!'}
  validates :name, format: { :with => /\A[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]\Z/,
                             :message => 'Nome inválido. Não é permitido a utilização dos caracteres especiais'}
end

app/models/upload_file.rb
class UploadFile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: { message: "É obrigatório informar o nome!" }
    validates :email, presence: { message: "É obrigatório informar o email!" }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Formato de e-mail inválido!" }
    validates :password, presence: { message: "É obrigatório informar uma senha!" }
    validates_presence_of :name
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
    @about = About.all
  end

  def create
    @about = About.new(about_params)
    if @about.save
      redirect_to about_path, notice: "Sua sugestão foi recebida por nossa equipe, agradecemos a colaboração!"
    else
      redirect_to about_path, notice: "É obrigatório inserir algum texto no campo de sugestões!"
    end
  end

    def about_params
      params.require(:about).permit(:sugestao)
    end
end

app/controllers/buscar_controller.rb
class BuscarController < ApplicationController
    def index
     @diretorio = Diretorio.all
   end

   def search
      @diretorio = Diretorio.where("name LIKE ?", "%" + params[:name] + "%")
   end

  def show
    @diretorio = Diretorio.where("name LIKE ?", "%" + params[:name] + "%")
    if params[:name].blank?
       redirect_to buscar_path, notice: "Por favor insira nome válido"
    elsif params[:name].present?
       @diretorio = Diretorio.where("name LIKE ?", "%" + params[:name] + "%")
    end
  end

   def busca_params
     params.require(:diretorio).permit(:name)
   end
end

app/controllers/campi_controller.rb
class CampiController < ApplicationController
  before_action :set_campi, only: %i[ show edit update destroy ]
  # GET /campi or /campi.json
  def index
    @campi = Campi.where.not(name: 'root')
  end

  # GET /campi/1 or /campi/1.json
  def show
    @campi_mapa = CampiMapa.new
  end

  # GET /campi/new
  def new
    @campi = Campi.new
    @campi = Campi.all

    @campi_parent_id = params[:campi_parent_id]
  end

  # GET /campi/1/edit
  def edit
    @campi = Campi.where.not(id: @campi.id)
  end

  # Only allow a list of trusted parameters through.
  def campi_params
    params.require(:campi).permit(:name, :path)
  end
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
    def perfil
        checkSession()
    end
    def editprofile
        if session[:user_id] == nil
            redirect_to login_path
        else
            if Current.user.update(user_params)
                redirect_to perfil_path, notice: 'Perfil atualizado com sucesso!'
            else
                render :perfil, status: 422
            end
        end
    end
    def checkSession
        if session[:user_id] == nil
            redirect_to login_path
        else
            showData()
        end
    end
    def showData
        user = User.where(id: session[:user_id])
    end

    private
    
    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diretorios_helper.rb
module DiretoriosHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/upload_files_helper.rb
module UploadFilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buscar/new.html.erb
<h1>Buscar Diretório</h1>
<div class="errors">
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
</div>
<%= form_with model: @diretorio, url:buscar_path,local: true, data: { turbo: false } do |form| %>
    <div class="mb-3">
        <%= form.label :buscar, "Buscar"%>
        <%= form.text_field :name, class: "form-control", placeholder: "Digite o nome do Diretório Aqui" %>
    </div>

    <div class="mb-3">
        <%= form.submit "buscar", class: "btn btn-primary"  %>
    </div>
<% end %>

app/views/buscar/show.html.erb
<h1>Resultado</h1>

<p>
  <% if @diretorio.present? %>
    <%= render @diretorio %>
  <% else %>
    <p> Diretório não encontrado, por favor tente novamente. <p>
  <% end %>

  <div class = "mb-3">
      <%= link_to "Voltar", buscar_path, class: "btn-outline-secondary"  %>
  </div>
</p>

app/views/campi/_campi.html.erb
<div id="<%= dom_id campi %>">
  <%= link_to campi do %>
  <li class="list-group-item d-flex justify-content-between align-content-center">
    <div class="d-flex flex-row">
      <img src="https://img.icons8.com/color/100/000000/folder-invoices.png" width="40" />
      <div class="ml-2">
        <h6 class="mb-0"><%= campi.name %></h6>
        <div class="about">
          <span><%= campi.path %></span>
        </div>
      </div>
    </div>
  </li>
  <% end %>
</div>

app/views/campi/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }
      .button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 140px;
          font-size: 12px;
          text-decoration: none;
      }
      .link-text{
          text-decoration:none;
          color:white;
      }
  </style>
</head>
<body class="text-white">
<p style="color: green"><%= notice %></p>

<h1><icon class="bi bi-globe"></icon> Campi</h1>

<div id="diretorios">
  <% @campi.each do |campi| %>
    <p>
      <icon class="bi bi-folder"/>
      <%= link_to campi.name, campi, class:"link-text" %>
    </p>
  <% end %>
</div>
<br/>
</body>

app/views/campi/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }

      .list-group{
          padding-left: 30px;
          padding-right: 30px;
          width: 700px !important;
          max-height: 500px;
          min-height: 500px;
          overflow-y: auto;
      }

      .container-list {
          margin-top: 70px;
          border: 1px solid #6a95ea;
          border-radius: 20px;
          padding-bottom: 20px;
          padding-top: 10px;
      }

      .ml-2 {
          padding-left: 10px;
          color: #d2deff;
      }


      .list-group-item{
          margin-top:10px;
          border-radius: 10px;
          background: #5E35B1;
          cursor: pointer;
          transition: all 0.01s ease-in-out;
      }

      .list-group-item:hover{
          transform: scaleX(1.02);
      }

      .list-group-item:hover .check {
          opacity: 1;
      }

      .about span{
          font-size: 12px;
          margin-right: 10px;
      }

      input[type=checkbox] {
          position: relative;
          cursor: pointer;
      }

      input[type=checkbox]:before {
          content: "";
          display: block;
          position: absolute;
          width: 20px;
          height: 20px;
          top: 0px;
          left: 0;
          border: 1px solid #10a3f9;
          border-radius: 3px;
          background-color: white;
      }

      input[type=checkbox]:checked:after {
          content: "";
          display: block;
          width: 7px;
          height: 12px;
          border: solid #007bff;
          border-width: 0 2px 2px 0;
          -webkit-transform: rotate(45deg);
          -ms-transform: rotate(45deg);
          transform: rotate(45deg);
          position: absolute;
          top: 2px;
          left: 6px;
      }

      /* Full-width input fields */
      .form-container input[type=text], .form-container input[type=password] {
          width: 100%;
          padding: 15px;
          margin: 5px 0 22px 0;
          border: none;
          background: #f1f1f1;
      }

      /* When the inputs get focus, do something */
      .form-container input[type=text]:focus, .form-container input[type=password]:focus {
          background-color: #ddd;
          outline: none;
      }

      /* Set a style for the submit/login button */
      .form-container .open-button {
          background-color: #04AA6D;
          color: white;
          padding: 16px 20px;
          border: none;
          cursor: pointer;
          width: 100%;
          margin-bottom:10px;
          opacity: 0.8;
      }

      .open-button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 280px;
          font-size: 20px;
      }

      .side_buttons {
          height: 100px;
          width: 100px;
          margin: 20px;
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 30px;
          color: white;
      }

      .containers_button_on_the_side {
          width: 150px;
          vertical-align: middle;
          display: flex;
          align-items: center;
          justify-content: center;
      }

      /* Add a red background color to the cancel button */
      .form-container .cancel {
          background-color: red;
      }

      /* Add some hover effects to buttons */
      .form-container .open-button:hover, .side_buttons:hover {
          opacity: 1;
      }

      .open-button:hover, .side_buttons:hover {
          opacity: 1;
          background-color: black;
      }

      input[type="checkbox"]:checked + .check { opacity: 1; }
  </style>
</head>
<body>
<div class="container d-flex justify-content-center">
  <p style="color: white">
    <strong><%= @campi.name %></strong>
  </p>
</div>
<div class="container d-flex justify-content-center" style="color: white">
  <strong>Caminho: </strong>
  <%= @campi.path %>
</div>

<div class="contain er d-flex justify-content-center">

  <div class="containers_button_on_the_side">
    <% if Campi.new.get_root_campi_id != @campi.id %>
      <%= link_to campi_url(@campi_mapa.get_parent_campi(@campi.id).id) do %>
          <button class="side_buttons" id="back_button">Back</button>
      <% end %>
    <% else %>

    <% end %>
  </div>


<!--  Campi.find(CampiMapa.where(child: @campi.id)[:parent])-->

  <div class="container-list">
    <ul class="list-group mt-3 mb-3 text-white">

      <% CampiMapa.where(parent: @campi.id).each do |campi_in_selected_campi| %>
        <%= render Campi.where(id: campi_in_selected_campi.child) %>
      <% end %>

    </ul>
  </div>

  <div class="containers_button_on_the_side">
<!--    <button class="side_buttons", id="next_button">....</button>-->
  </div>

</div>

<script type="text/javascript" charset="utf-8">
</script>
</body>
</html>

app/views/perfil/perfil.html.erb
<style>
body{
    background: #1a0c50;
}
.card{
    display: grid;
    margin-top: 12vh;
    grid-template-rows: 40vh 23vh;
    grid-template-columns: 30vw;
    row-gap: 0.7vh;
    justify-content: center;
    background-image: linear-gradient(to right, #C9D6FF, #E2E2E2);
}
.user-information{
    display: grid;
    grid-template-columns: 5vw auto;
    row-gap: 2vh;
    grid-auto-rows: 4vh;
}
.img-profile{
    width: 100%;
    height: 100%;
    object-fit: contain;
}
.btn-save{
    grid-column-start: 1;
    grid-column-end: 3;
}
p{
    text-align: center;
    font-size: 1.5em;
}
</style>
<p style="color: green"><%= notice %></p>

<section class="card">
    <div class="user-image">
        <img class="img-profile" src="https://source.unsplash.com/random" />
    </div>
    <%= form_with model: Current.user, url: editprofile_path do |form| %>
    <div class="user-information">
            <span class="input-group-text" id="basic-addon1">Email</span>
            <%= form.text_field :email,  class: "form-control", type: "text", id: "Email", value: Current.user.email  %>
            <span class="input-group-text" id="basic-addon1">Nome</span>
            <%= form.text_field :name,  class: "form-control", type: "text", id: "Name", value: Current.user.name  %>
            <span class="input-group-text" id="basic-addon1">Senha</span>
            <%= form.text_field :password,  class: "form-control", type: "password", id: "Password", value: Current.user.password  %>
            <%= form.button "Salvar", class: "btn btn-primary btn-save", id: "btnEditProfile" %>
    </div>
        <% Current.user.errors.full_messages.each do |message| %>
            <div>ERRO: <%= message %></div>
        <% end %>
    <% end %>
</section>

app/views/welcome/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }

      .list-group{
          padding-left: 30px;
          padding-right: 30px;
          width: 700px !important;
          max-height: 500px;
          min-height: 500px;
          overflow-y: auto;
      }

      .welcome-text {
          padding: 10px;
          margin-top: 40px;
          border: 1px solid #6a95ea;
          border-radius: 20px;
          font-size: 12px;
          color: white;
          width: 700px !important;
          max-height: 300px;
          min-height: 300px;
          text-align: justify;
      }

      .welcome-title {
          color: #6a95ea;
          font-size: 36px;
          font-style: oblique;
          text-align: center;
      }

      .container-list {
          margin-top: 70px;
          border: 1px solid #6a95ea;
          border-radius: 20px;
          padding-bottom: 20px;
          padding-top: 10px;
          max-width: 700px;
          min-width: 700px;
      }

      .ml-2 {
          padding-left: 10px;
          color: #d2deff;
      }


      .list-group-item{
          margin-top:10px;
          border-radius: none;
          background: #5E35B1;
          cursor: pointer;
          transition: all 0.01s ease-in-out;
      }

      .list-group-item:hover{
          transform: scaleX(1.02);
      }

      .check{
          opacity: 0;
          transition: all 0.6s ease-in-out;
      }

      .list-group-item:hover .check {
          opacity: 1;
      }

      .about span{
          font-size: 12px;
          margin-right: 10px;
      }

      input[type=checkbox] {
          position: relative;
          cursor: pointer;
      }

      input[type=checkbox]:before {
          content: "";
          display: block;
          position: absolute;
          width: 20px;
          height: 20px;
          top: 0px;
          left: 0;
          border: 1px solid #10a3f9;
          border-radius: 3px;
          background-color: white;
      }

      input[type=checkbox]:checked:after {
          content: "";
          display: block;
          width: 7px;
          height: 12px;
          border: solid #007bff;
          border-width: 0 2px 2px 0;
          -webkit-transform: rotate(45deg);
          -ms-transform: rotate(45deg);
          transform: rotate(45deg);
          position: absolute;
          top: 2px;
          left: 6px;
      }

      input[type="checkbox"]:checked + .check { opacity: 1; }
  </style>
</head>
<body>

<div class="container d-flex justify-content-center flex-column">

  <div class="welcome-text">
    <p class="welcome-title">Bem-vindo ao USPShare!</p>
    <p>A USPShare é sua plataforma para compartilhar materiais, arquivos, listas e tudo relacionado a disciplinas
    da graduação e pós graduação. Feito de alunos da USP para alunos da USP, que sabem na pele quão frustrante pode
    ser se preparar para uma prova ou atividade acadêmica sem ter o material necessário.</p>
    <p><b>AVISO IMPORTANTE:</b> O compartilhamento de provas NÃO é permitido nessa plataforma caso não haja aval
    do docente da disciplina.</p>
  </div>

  <div class="container-list">
    <ul class="list-group mt-3 mb-3 text-white">

      <% DiretoriosMapa.where(parent: Diretorio.where(name: 'root').ids[0]).each do |diretorio_in_root| %>
        <%= render Diretorio.where(id: diretorio_in_root.child, flPublic:true) %>
      <% end %>

    </ul>
  </div>


</div>
</body>
</html>

app/views/welcome/signup.html.erb
<section class="text-center text-lg-start centered">
  <style>
    body{
        background: #1a0c50;
    }

    .cascading-right {
      margin-right: 20px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>

  <div class="container py-4">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Registre-se!</h2>
            <form>
                <div class="form-floating mb-4">
                    <input type="text" id="form3Example1" class="form-control" />
                    <label class="form-label" for="form3Example1">Usuário</label>
                </div>

              <div class="form-floating mb-4">
                <input type="email" id="form3Example3" class="form-control" />
                <label class="form-label" for="form3Example3">Email</label>
              </div>

              <div class="form-floating mb-4">
                <input type="password" id="form3Example4" class="form-control" />
                <label class="form-label" for="form3Example4">Senha</label>
              </div>

              <div class="form-floating mb-4">
                <input type="password" id="form3Example4" class="form-control" />
                <label class="form-label" for="form3Example4">Confirmar senha</label>
              </div>

              <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary btn-block mb-4">
                Registrar
              </button>
              </div>

            </form>
          </div>
        </div>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-75 rounded-4 shadow-4"
          alt="" />
      </div>
    </div>
  </div>
</section>