config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :diretorios do
    member do
      delete :delete_diretorio
    end
  end

  get 'perfil', to: 'perfil#perfil'
  patch 'editprofile', to: 'perfil#editprofile'
  get 'meusDiretorios', to:'diretorios#userDirectories'
  get 'menu', to: 'welcome#index'
  get 'signup', to: 'registrations#new'
  get 'login', to: 'registrations#login'
  get 'loginTest', to: 'registrations#loginTest'
  get 'campi', to: 'campi#index'
  post 'login', to: 'registrations#makeLogin'
  post 'signup', to: 'registrations#create'
  delete 'logout', to: 'sessions#destroy'
  resources :registrations


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :buscar_diretorio
  get 'buscar', to: 'buscar#new'
  post 'buscar', to: 'buscar#show'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'

  resources :about_page
  get 'about', to: 'about#index'
  post 'about', to: 'about#create'

  resources :upload_files


end

app/models/diretorio.rb
class Diretorio < ApplicationRecord
  validates :name, presence: { message: 'É obrigatório informar o nome!'}
  validates :name, format: { :with => /\A[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]\Z/,
    :message => 'Nome inválido. Não é permitido a utilização dos caracteres especiais'}
  ##validates :name, format: { :with => /A(?!root$)z/,
  ##                          :message => 'Nome reservado. root é o nome para o diretório raiz'}


  def get_root_directory_id
    @diretorio_root = Diretorio.where(name: 'root').ids[0]

    if @diretorio_root == nil
      create_root_directory.id
    else
      @diretorio_root
    end
  end

  def get_root_directory
    @root_id = get_root_directory_id

    if @root_id == nil
      create_root_directory
    else
      Diretorio.find(@root_id)
    end
  end

  def create_root_directory
    @diretorio_root = Diretorio.new({name: 'root', path: '/'})
    @diretorio_root.save
    @diretorio_root
  end
end

app/controllers/diretorios_controller.rb
class DiretoriosController < ApplicationController
  before_action :set_diretorio, only: %i[ show edit update destroy ]
  $rootId = 1
  # GET /diretorios or /diretorios.json
  def index
    @diretorios = Diretorio.where.not(name: 'root')
  end

  # GET /diretorios/1 or /diretorios/1.json
  def show
    @diretorio_mapa = DiretoriosMapa.new
  end

  #GET /meusDiretorios
  def userDirectories
    @diretorios = Diretorio.where(userId: session[:user_id])
  end

  # GET /diretorios/new
  def new
    @diretorio = Diretorio.new
    @diretorios = Diretorio.all

    @diretorio_parent_id = params[:diretorio_parent_id]
  end

  # GET /diretorios/1/edit
  def edit
    @diretorios = Diretorio.where.not(id: @diretorio.id)
  end

  # POST /diretorios or /diretorios.json
  def create
    @diretorio = Diretorio.new(diretorio_params)
    if @diretorio.created_at == nil
      @diretorio.created_at = Time.now
    end
    @parent_id = params[:diretorio][:parent_ID]

    if params[:flPublic] == false
      @diretorio.userId = session[:user_id]
    end
    if params[:flPublic] == nil
      @diretorio.flPublic = true
    end

    respond_to do |format|
      if @diretorio.save
        if @parent_id == nil or @parent_id == ""
          @parent_id = $rootId
        end

        @diretorio_mapa = DiretoriosMapa.new({:parent => @parent_id, :child => @diretorio.id})

        if @diretorio_mapa.save
          format.html { redirect_to diretorio_url(Diretorio.find(@parent_id)), notice: "Diretorio foi criado com sucesso." }
          format.json { render :show, status: :created, location: @diretorio }
        end
      else
        @diretorios = Diretorio.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diretorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diretorios/1 or /diretorios/1.json
  def update
    if (params[:flPublic] == nil or params[:flPublic] == false) and @diretorio.userId == nil
      @diretorio.userId = session[:user_id]
      if params[:flPublic] == nil
        @diretorio.flPublic = true
      end
    end

    respond_to do |format|
      if @diretorio.update(diretorio_params)
        format.html { redirect_to diretorio_url(@diretorio), notice: "Diretorio foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @diretorio }
      else
        @diretorios = Diretorio.where.not(id: @diretorio.id)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diretorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diretorios/1 or /diretorios/1.json
  def destroy
    @diretorio.destroy

    respond_to do |format|
      format.html { redirect_to diretorios_url, notice: "Diretorio foi excluido com sucesso." }
      format.json { head :no_content }
    end
  end
  def delete_diretorio
    Diretorio.destroy(params[:id])

    respond_to do |format|
      format.html { redirect_to diretorios_url, notice: "Diretorio foi excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diretorio
      @diretorio = Diretorio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diretorio_params
      params.require(:diretorio).permit(:name, :path, :flPublic)
    end
end

app/helpers/diretorios_helper.rb
module DiretoriosHelper
end

app/views/diretorios/_diretorio.html.erb
<div id="<%= dom_id diretorio %>">
  <%= link_to diretorio do %>
  <li class="list-group-item d-flex justify-content-between align-content-center">
    <div class="d-flex flex-row">
      <img src="https://img.icons8.com/color/100/000000/folder-invoices.png" width="40" />
      <div class="ml-2">
        <h6 class="mb-0"><%= diretorio.name %></h6>
        <div class="about">
          <span><%= diretorio.path %></span>
        </div>
      </div>
    </div>
  </li>
  <% end %>
</div>

app/views/diretorios/_form.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }
      .button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 140px;
          font-size: 12px;
          text-decoration: none;
      }
  </style>
</head>
<body class="text-white">
<%= form_with(model: diretorio, local: true) do |form| %>
  <% if diretorio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(diretorio.errors.count, "erro(s)") %> impedem que o diretório seja salvo:</h2>

      <ul>
        <% diretorio.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Nome", style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <br/>
  <div>
    <%= form.label :path, "Caminho", style: "display: block" %>
    <%= form.select :path, @diretorios.map { |d| [d.name, d.name == 'root' ?  d.path + d.name : d.path+'/'+d.name]}%>
  </div>
  <br/>
  <br/>
  <div>
    <%= form.label :flPublic, "Público", style: "display: block" %><br/>
    <%= form.label :flPublic, 'Sim', value: "true" %>
    <%= form.radio_button :flPublic, true %>
    <%= form.label :flPublic, 'Não', value: "false" %>
    <%= form.radio_button :flPublic, false %>
  </div>
  <br/>
  <br/>
  <div>
    <%= form.hidden_field :parent_ID, :value => @diretorio_parent_id %>
    <%= form.submit 'Salvar Diretório', class: "button" %>
  </div>
  <br/>
<% end %>
</body>

app/views/diretorios/edit.html.erb
<h1>Editando Diretório</h1>

<%= render "form", diretorio: @diretorio %>

<br>

<div>
  <%= link_to "Mostrar", @diretorio %> |
  <% if not !Current.user %>
    <%= link_to "Voltar para Meus Diretorios", '/meusDiretorios'%>
  <% end %>
  <% if not Current.user %>
    <%= link_to "Voltar ao Índice", diretorios_path %>
  <% end %>
</div>

app/views/diretorios/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }
      .button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 140px;
          font-size: 12px;
          text-decoration: none;
      }
      .link-text{
          text-decoration:none;
          color:white;
      }
  </style>
</head>
<body class="text-white">
<p style="color: green"><%= notice %></p>

<h1><icon class="bi bi-folder"></icon> Diretorios</h1>

<div id="diretorios">
  <% @diretorios.each do |diretorio| %>
    <p>
      <%= link_to '', delete_diretorio_diretorio_url(diretorio.id), class:"bi bi-trash link-text", data: { "turbo_confirm": 'Tem certeza?', "turbo-method": :delete }%>
      <icon class="bi bi-folder"/>
      <%= link_to diretorio.name, diretorio, class:"link-text" %>
    </p>
  <% end %>
</div>
<br/>
<%= link_to "Criar Diretório", new_diretorio_path, class: "button" %>
</body>

app/views/diretorios/new.html.erb
<h1>Novo Diretório</h1>

<%= render "form", diretorio: @diretorio, parent: @diretorio_parent_id %>

<br>

<div>
  <% if not !Current.user %>
    <%= link_to "Voltar para Meus Diretorios", '/meusDiretorios'%>
  <% end %>
  <% if not Current.user %>
    <%= link_to "Voltar para Diretorios", diretorios_path %>
  <% end %>
</div>

app/views/diretorios/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }

      .list-group{
          padding-left: 30px;
          padding-right: 30px;
          width: 700px !important;
          max-height: 500px;
          min-height: 500px;
          overflow-y: auto;
      }

      .container-list {
          margin-top: 70px;
          border: 1px solid #6a95ea;
          border-radius: 20px;
          padding-bottom: 20px;
          padding-top: 10px;
      }

      .ml-2 {
          padding-left: 10px;
          color: #d2deff;
      }


      .list-group-item{
          margin-top:10px;
          border-radius: 10px;
          background: #5E35B1;
          cursor: pointer;
          transition: all 0.01s ease-in-out;
      }

      .list-group-item:hover{
          transform: scaleX(1.02);
      }

      .list-group-item:hover .check {
          opacity: 1;
      }

      .about span{
          font-size: 12px;
          margin-right: 10px;
      }

      input[type=checkbox] {
          position: relative;
          cursor: pointer;
      }

      input[type=checkbox]:before {
          content: "";
          display: block;
          position: absolute;
          width: 20px;
          height: 20px;
          top: 0px;
          left: 0;
          border: 1px solid #10a3f9;
          border-radius: 3px;
          background-color: white;
      }

      input[type=checkbox]:checked:after {
          content: "";
          display: block;
          width: 7px;
          height: 12px;
          border: solid #007bff;
          border-width: 0 2px 2px 0;
          -webkit-transform: rotate(45deg);
          -ms-transform: rotate(45deg);
          transform: rotate(45deg);
          position: absolute;
          top: 2px;
          left: 6px;
      }

      /* Full-width input fields */
      .form-container input[type=text], .form-container input[type=password] {
          width: 100%;
          padding: 15px;
          margin: 5px 0 22px 0;
          border: none;
          background: #f1f1f1;
      }

      /* When the inputs get focus, do something */
      .form-container input[type=text]:focus, .form-container input[type=password]:focus {
          background-color: #ddd;
          outline: none;
      }

      /* Set a style for the submit/login button */
      .form-container .open-button {
          background-color: #04AA6D;
          color: white;
          padding: 16px 20px;
          border: none;
          cursor: pointer;
          width: 100%;
          margin-bottom:10px;
          opacity: 0.8;
      }

      .open-button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 280px;
          font-size: 20px;
      }

      .side_buttons {
          height: 100px;
          width: 100px;
          margin: 20px;
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 30px;
          color: white;
      }

      .containers_button_on_the_side {
          width: 150px;
          vertical-align: middle;
          display: flex;
          align-items: center;
          justify-content: center;
      }

      /* Add a red background color to the cancel button */
      .form-container .cancel {
          background-color: red;
      }

      /* Add some hover effects to buttons */
      .form-container .open-button:hover, .side_buttons:hover {
          opacity: 1;
      }

      .open-button:hover, .side_buttons:hover {
          opacity: 1;
          background-color: black;
      }

      input[type="checkbox"]:checked + .check { opacity: 1; }
  </style>
</head>
<body>
<div class="container d-flex justify-content-center">
  <p style="color: white">
    <strong><%= @diretorio.name %></strong>
  </p>
</div>
<div class="container d-flex justify-content-center" style="color: white">
  <strong>Caminho: </strong>
  <%= @diretorio.path %>
</div>

<div class="container d-flex justify-content-center">

  <div class="containers_button_on_the_side">
    <% if Diretorio.new.get_root_directory_id != @diretorio.id %>
      <%= link_to diretorio_url(@diretorio_mapa.get_parent_directory(@diretorio.id).id) do %>
          <button class="side_buttons" id="back_button">Back</button>
      <% end %>
    <% else %>

    <% end %>
  </div>


<!--  Diretorio.find(DiretoriosMapa.where(child: @diretorio.id)[:parent])-->

  <div class="container-list">
    <ul class="list-group mt-3 mb-3 text-white">

      <% DiretoriosMapa.where(parent: @diretorio.id).each do |diretorios_in_selected_diretorio| %>
        <%= render Diretorio.where(id: diretorios_in_selected_diretorio.child, flPublic:true) %>
      <% end %>

    </ul>
  </div>

  <div class="containers_button_on_the_side">
<!--    <button class="side_buttons", id="next_button">....</button>-->
  </div>

</div>

<div class="container-buttons d-flex justify-content-center">

  <%= link_to edit_diretorio_path(@diretorio) do %>
    <button id="edit-button" class="open-button">Editar</button>
  <% end %>

  <%= link_to new_diretorio_path(:diretorio_parent_id => @diretorio.id) do %>
    <button class="open-button">Criar</button>
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
</script>
</body>
</html>

app/views/diretorios/userDirectories.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }
      .button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 140px;
          font-size: 12px;
          text-decoration: none;
      }
      .link-text{
          text-decoration:none;
          color:white;
      }
  </style>
</head>
<body class="text-white">
<p style="color: green"><%= notice %></p>

<h1><icon class="bi bi-folder"></icon> Diretorios</h1>

<div id="diretorios">
  <% @diretorios.each do |diretorio| %>
    <p>
      <%= link_to '', delete_diretorio_diretorio_url(diretorio.id), class:"bi bi-trash link-text", data: { "turbo_confirm": 'Tem certeza?', "turbo-method": :delete }%>
      <icon class="bi bi-folder"/>
      <%= link_to diretorio.name, diretorio, class:"link-text" %>
    </p>
  <% end %>
</div>
<br/>
<%= link_to "Criar Diretório", new_diretorio_path, class: "button" %>
</body>