config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :diretorios do
    member do
      delete :delete_diretorio
    end
  end

  get 'perfil', to: 'perfil#perfil'
  patch 'editprofile', to: 'perfil#editprofile'
  get 'meusDiretorios', to:'diretorios#userDirectories'
  get 'menu', to: 'welcome#index'
  get 'signup', to: 'registrations#new'
  get 'login', to: 'registrations#login'
  get 'loginTest', to: 'registrations#loginTest'
  get 'campi', to: 'campi#index'
  post 'login', to: 'registrations#makeLogin'
  post 'signup', to: 'registrations#create'
  delete 'logout', to: 'sessions#destroy'
  resources :registrations


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :buscar_diretorio
  get 'buscar', to: 'buscar#new'
  post 'buscar', to: 'buscar#show'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'

  resources :about_page
  get 'about', to: 'about#index'
  post 'about', to: 'about#create'

  resources :upload_files


end

app/models/about.rb
class About < ApplicationRecord
  validates :sugestao, presence: { message: "Sua sugestão foi recebida por nossa equipe, agradecemos a colaboração!"}
  validates :sugestao, presence: { message: "É obrigatório inserir algum texto no campo de sugestões!"}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buscar.rb
class Buscar < ApplicationRecord
    validates :buscar, presence: { message: "Por favor insira nome válido" }
    validates :buscar, presence: {message: "Diretório não encontrado, por favor tente novamente."}
end

app/models/campi.rb
class Campi < ApplicationRecord
  validates :name, presence: { message: 'É obrigatório informar o nome!'}
  validates :name, format: { :with => /\A[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]\Z/,
                             :message => 'Nome inválido. Não é permitido a utilização dos caracteres especiais'}
  ##validates :name, format: { :with => /A(?!root$)z/,
  ##                          :message => 'Nome reservado. root é o nome para o diretório raiz'}

end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/diretorio.rb
class Diretorio < ApplicationRecord
  validates :name, presence: { message: 'É obrigatório informar o nome!'}
  validates :name, format: { :with => /\A[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]\Z/,
    :message => 'Nome inválido. Não é permitido a utilização dos caracteres especiais'}
  ##validates :name, format: { :with => /A(?!root$)z/,
  ##                          :message => 'Nome reservado. root é o nome para o diretório raiz'}


  def get_root_directory_id
    @diretorio_root = Diretorio.where(name: 'root').ids[0]

    if @diretorio_root == nil
      create_root_directory.id
    else
      @diretorio_root
    end
  end

  def get_root_directory
    @root_id = get_root_directory_id

    if @root_id == nil
      create_root_directory
    else
      Diretorio.find(@root_id)
    end
  end

  def create_root_directory
    @diretorio_root = Diretorio.new({name: 'root', path: '/'})
    @diretorio_root.save
    @diretorio_root
  end
end

app/models/diretorios_mapa.rb
class DiretoriosMapa < ApplicationRecord
  def get_parent_directory(directory_id)
    if directory_id == Diretorio.new.get_root_directory_id
      Diretorio.new.get_root_directory
    else
      @diretorio_mapa = DiretoriosMapa.find_by(child: directory_id)

      if @diretorio_mapa != nil
        return Diretorio.where(id: @diretorio_mapa[:parent])[0]
      else
        return Diretorio.new.get_root_directory
      end
    end
  end

  def parent_is_root(directory_id)
    get_parent_directory(directory_id).id == Diretorio.new.get_root_directory_id
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :name, presence: { message: 'É obrigatório informar o nome!'}
  validates :name, format: { :with => /\A[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]\Z/,
                             :message => 'Nome inválido. Não é permitido a utilização dos caracteres especiais'}
end

app/models/upload_file.rb
class UploadFile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: { message: "É obrigatório informar o nome!" }
    validates :email, presence: { message: "É obrigatório informar o email!" }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Formato de e-mail inválido!" }
    validates :password, presence: { message: "É obrigatório informar uma senha!" }
    validates_presence_of :name
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
    @about = About.all
  end

  def create
    @about = About.new(about_params)
    if @about.save
      redirect_to about_path, notice: "Sua sugestão foi recebida por nossa equipe, agradecemos a colaboração!"
    else
      redirect_to about_path, notice: "É obrigatório inserir algum texto no campo de sugestões!"
    end
  end

    def about_params
      params.require(:about).permit(:sugestao)
    end
end

app/controllers/buscar_controller.rb
class BuscarController < ApplicationController
    def index
     @diretorio = Diretorio.all
   end

   def search
      @diretorio = Diretorio.where("name LIKE ?", "%" + params[:name] + "%")
   end

  def show
    @diretorio = Diretorio.where("name LIKE ?", "%" + params[:name] + "%")
    if params[:name].blank?
       redirect_to buscar_path, notice: "Por favor insira nome válido"
    elsif params[:name].present?
       @diretorio = Diretorio.where("name LIKE ?", "%" + params[:name] + "%")
    end
  end

   def busca_params
     params.require(:diretorio).permit(:name)
   end
end

app/controllers/campi_controller.rb
class CampiController < ApplicationController
  before_action :set_campi, only: %i[ show edit update destroy ]
  # GET /campi or /campi.json
  def index
    @campi = Campi.where.not(name: 'root')
  end

  # GET /campi/1 or /campi/1.json
  def show
    @campi_mapa = CampiMapa.new
  end

  # GET /campi/new
  def new
    @campi = Campi.new
    @campi = Campi.all

    @campi_parent_id = params[:campi_parent_id]
  end

  # GET /campi/1/edit
  def edit
    @campi = Campi.where.not(id: @campi.id)
  end

  # Only allow a list of trusted parameters through.
  def campi_params
    params.require(:campi).permit(:name, :path)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diretorios_helper.rb
module DiretoriosHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/upload_files_helper.rb
module UploadFilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">USP Share</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to '<i class="bi bi-house-door"></i> Menu' .html_safe, menu_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
        <%= link_to '<icon class="bi bi-globe"/>Campi' .html_safe, campi_path, class: "nav-link active" %>
        </li>
        <% if not !Current.user %>
          <li class="nav-item">
            <%= link_to '<i class="bi bi-folder"></i> Seus Diretórios' .html_safe, '/meusDiretorios', class: "nav-link active me-3" %>
          </li>
        <% end %>
        <% if Current.user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-pencil-square"></i>
              ADM
            </a>
            <ul class="dropdown-menu bg-dark text-white">
              <li><%= link_to '<icon class="bi bi-folder"/>  Diretórios' .html_safe, diretorios_path, class: "nav-link active" %></li>
              <li><%= link_to '<icon class="bi bi-book"/>  Matérias' .html_safe, subjects_path, class: "nav-link active" %></li>
            </ul>
          </li>
        <% end %>
        <li class="nav-item">
        <%= link_to '<i class="bi bi-search"></i> Buscar' .html_safe, buscar_path, class: "nav-link active me-3" %>
        </li>
        <li class="nav-item">
        <%= link_to '<i class="bi bi-browser-safari"></i> About Us' .html_safe, about_path, class: "nav-link active" %>
        </li>
      </ul>
      <form class="d-flex text-white" role="search">
          <% if Current.user %>
            <%= link_to '<i class="bi bi-file-earmark-person me-2"></i>Perfil' .html_safe, perfil_path, class: "nav-link active me-3 perfilUser" %>
          <% else %>
            <%= link_to '<i class="bi bi-box-arrow-in-right me-2"></i>Login' .html_safe, login_path, class: "nav-link active me-3" %>
            <%= link_to '<i class="bi bi-door-open me-2"></i>Cadastro' .html_safe, signup_path, class: "nav-link active me-3" %>
          <% end %>
      </form>
      <% if not !Current.user %>
      <%= button_to '<i class="bi bi-box-arrow-in-right me-2"></i>Deslogar' .html_safe, logout_path, method: :delete, class: "nav-link active me-3" %>
      <% end %>
    </div>
  </div>
</nav>