config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :diretorios do
    member do
      delete :delete_diretorio
    end
  end

  get 'perfil', to: 'perfil#perfil'
  patch 'editprofile', to: 'perfil#editprofile'
  get 'meusDiretorios', to:'diretorios#userDirectories'
  get 'menu', to: 'welcome#index'
  get 'signup', to: 'registrations#new'
  get 'login', to: 'registrations#login'
  get 'loginTest', to: 'registrations#loginTest'
  get 'campi', to: 'campi#index'
  post 'login', to: 'registrations#makeLogin'
  post 'signup', to: 'registrations#create'
  delete 'logout', to: 'sessions#destroy'
  resources :registrations


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :buscar_diretorio
  get 'buscar', to: 'buscar#new'
  post 'buscar', to: 'buscar#show'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'

  resources :about_page
  get 'about', to: 'about#index'
  post 'about', to: 'about#create'

  resources :upload_files


end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :name, presence: { message: 'É obrigatório informar o nome!'}
  validates :name, format: { :with => /\A[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]+[a-zA-Z0-9 çãáâéêíóôú]\Z/,
                             :message => 'Nome inválido. Não é permitido a utilização dos caracteres especiais'}
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:name, :teacher, :campi)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }
      .button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 140px;
          font-size: 12px;
          text-decoration: none;
      }
  </style>
</head>
<body class="text-white">
  <%= form_with(model: subject) do |form| %>
    <% if subject.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(subject.errors.count, "erro(s)") %> impedem que a matéria seja salva:</h2>

        <ul>
          <% subject.errors.each do |error| %>
            <li><%= error.message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, "Nome",style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  <br/>
    <div>
      <%= form.label :teacher, "Professor", style: "display: block" %>
      <%= form.text_field :teacher %>
    </div>
    <br/>
    <div>
      <%= form.label :campi, "Campi", style: "display: block" %>
      <%= form.text_field :campi %>
    </div>
    <br/><br/>
    <div>
      <%= form.submit 'Salvar Matéria', class: "button" %>
    </div>
  <% end %>
</body>

app/views/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
  <%= link_to subject do %>
    <li class="list-group-item d-flex justify-content-between align-content-center">
      <div class="d-flex flex-row">
        <i class="bi bi-book"></i>
        <div class="ml-2">
          <h6 class="mb-0"><%= subject.name %></h6>
        </div>
      </div>
    </li>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<h1>Editando Matéria</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Mostrar", @subject %> |
  <%= link_to "Voltar ao Índice", subjects_path %>
</div>

app/views/subjects/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }
      .button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 140px;
          font-size: 12px;
          text-decoration: none;
      }
      .link-text{
          text-decoration:none;
          color:white;
      }
  </style>
</head>
<body class="text-white">
    <p style="color: green"><%= notice %></p>

    <h1><icon class="bi bi-book"></icon> Matérias</h1>

    <div id="subjects">
      <% @subjects.each do |subject| %>
        <p>
          <icon class="bi bi-book"/>
          <%= link_to subject.name, subject, class:"link-text" %>
        </p>
      <% end %>
    </div>
    <br/>
    <%= link_to "Criar Matéria", new_subject_path, class:"button" %>
</body>

app/views/subjects/new.html.erb
<h1>Nova Matéria</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Voltar para Matérias", subjects_path %>
</div>

app/views/subjects/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
      body{
          background: #1a0c50;
      }

      .list-group{
          padding-left: 30px;
          padding-right: 30px;
          width: 700px !important;
          max-height: 500px;
          min-height: 500px;
          overflow-y: auto;
      }

      .container-list {
          margin-top: 70px;
          border: 1px solid #6a95ea;
          border-radius: 20px;
          padding-bottom: 20px;
          padding-top: 10px;
      }

      .ml-2 {
          padding-left: 10px;
          color: #d2deff;
      }


      .list-group-item{
          margin-top:10px;
          border-radius: 10px;
          background: #5E35B1;
          cursor: pointer;
          transition: all 0.01s ease-in-out;
      }

      .list-group-item:hover{
          transform: scaleX(1.02);
      }

      .list-group-item:hover .check {
          opacity: 1;
      }

      .about span{
          font-size: 12px;
          margin-right: 10px;
      }

      input[type=checkbox] {
          position: relative;
          cursor: pointer;
      }

      input[type=checkbox]:before {
          content: "";
          display: block;
          position: absolute;
          width: 20px;
          height: 20px;
          top: 0px;
          left: 0;
          border: 1px solid #10a3f9;
          border-radius: 3px;
          background-color: white;
      }

      input[type=checkbox]:checked:after {
          content: "";
          display: block;
          width: 7px;
          height: 12px;
          border: solid #007bff;
          border-width: 0 2px 2px 0;
          -webkit-transform: rotate(45deg);
          -ms-transform: rotate(45deg);
          transform: rotate(45deg);
          position: absolute;
          top: 2px;
          left: 6px;
      }

      /* Full-width input fields */
      .form-container input[type=text], .form-container input[type=password] {
          width: 100%;
          padding: 15px;
          margin: 5px 0 22px 0;
          border: none;
          background: #f1f1f1;
      }

      /* When the inputs get focus, do something */
      .form-container input[type=text]:focus, .form-container input[type=password]:focus {
          background-color: #ddd;
          outline: none;
      }

      /* Set a style for the submit/login button */
      .form-container .open-button {
          background-color: #04AA6D;
          color: white;
          padding: 16px 20px;
          border: none;
          cursor: pointer;
          width: 100%;
          margin-bottom:10px;
          opacity: 0.8;
      }

      .open-button {
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 10px;
          margin-top: 20px;
          margin-right: 20px;
          color: white;
          padding: 16px 20px;
          cursor: pointer;
          opacity: 0.8;
          width: 280px;
          font-size: 20px;
      }

      .side_buttons {
          height: 100px;
          width: 100px;
          margin: 20px;
          border: 2px solid #6a95ea;
          background-color: rgba(7, 8, 35, 0.7);
          border-radius: 30px;
          color: white;
      }

      .containers_button_on_the_side {
          width: 150px;
          vertical-align: middle;
          display: flex;
          align-items: center;
          justify-content: center;
      }

      /* Add a red background color to the cancel button */
      .form-container .cancel {
          background-color: red;
      }

      /* Add some hover effects to buttons */
      .form-container .open-button:hover, .side_buttons:hover {
          opacity: 1;
      }

      .open-button:hover, .side_buttons:hover {
          opacity: 1;
          background-color: black;
      }

      input[type="checkbox"]:checked + .check { opacity: 1; }

      .link-text{
          text-decoration:none;
          color:white;
      }
  </style>
</head>
<body>
  <div class="container d-flex justify-content-center">
    <p style="color: white">
      <strong><%= @subject.name %></strong>
    </p>
  </div>
  <div class="container-list">
    <div class="container d-flex justify-content-center" style="color: white">
      <strong>Professor: </strong>
      <%= @subject.teacher %>
    </div>
    <br/>
    <div class="container d-flex justify-content-center" style="color: white">
      <strong>Campi: </strong>
      <%= @subject.campi %>
    </div>
  </div>

  <p style="color: green"><%= notice %></p>

  <div class="container-buttons d-flex justify-content-center">
    <%= link_to edit_subject_path(@subject)  do %>
      <button id="edit-button" class="open-button">Editar</button>
    <% end %>

    <%= link_to subjects_path do %>
      <button class="open-button">Voltar</button>
    <% end %>
  </div>
</body>